[문자열 계산기] 리뷰 요청 드립니다!
kiworkshop/java-string-calculator pull request #11
Opened 2021-06-14 16:08 UTC by seongbeenkim

안녕하세요 덕수 선생님!

1주차 미션 문자열 계산기 리뷰 요청 드립니다!

2021-06-14 22:49 UTC, Deocksoo requested changes
성빈님 안녕하세요 :) 리뷰이 김덕수입니다.
위에서 아래로 읽을 수 있도록 순서도 잘 배치해주시고, 네이밍도 깔끔하게 잘 작성해주셔서 편하게 읽었네요.
요구사항에 맞춰 깔끔하게 잘 작성해주신 것 같습니다 👍 
간단한 코멘트 몇 개 남겨드렸는데, 확인 한 번 부탁드려요~

2021-06-14 22:49 UTC, Deocksoo commented on src/main/java/calculator/StringCalculator.java
> +        String[] numbers = split(expression);
java Collection인 List 대신 array를 사용하도록 변경하신 이유가 있을까요~?

2021-06-14 22:49 UTC, Deocksoo commented on src/main/java/calculator/StringCalculator.java
> +        String customDelimeterRegex = "//(.)\n(.*)";
java 상수처리 컨벤션에 맞춰 정의하면 어떨까요?

2021-06-14 22:49 UTC, Deocksoo commented on src/main/java/calculator/StringCalculator.java
> +        String defaultDelimiterRegex = ",|:";
ditto

2021-06-15 01:57 UTC, seongbeenkim commented on src/main/java/calculator/StringCalculator.java
> +        String[] numbers = split(expression);
변경 전 코드를 보면서,
현재 코드에서 Collection인 List가 제공하는 기능들을 사용하지 않는데 굳이 감쌀 필요가 있을까?,
String.split() 함수 결과 타입을 동일하게 반환하는 것이 제가 만든 split()을 사용하는데 더 이해하기 쉽지 않을까?
라는 생각이 들어서 변경하게 되었습니다.

2021-06-15 01:57 UTC, seongbeenkim commented on src/main/java/calculator/StringCalculator.java
> +        String customDelimeterRegex = "//(.)\n(.*)";
넵넵 함수를 읽을 시 한 눈에 보기 좋지 않을까?라는 생각으로 내부에 변수로 선언해준 부분이었는데
말씀하신대로 상수로 재정의하였습니다! 감사합니다:)

2021-06-15 01:57 UTC, seongbeenkim commented on src/main/java/calculator/StringCalculator.java
> +        String defaultDelimiterRegex = ",|:";
이 부분도 재정의하였습니다!

2021-06-15 02:41 UTC, merged

2021-06-15 02:42 UTC, Deocksoo commented
내용 잘 반영해주신 것 같아 머지하겠습니다.