[문자열 계산기] 리뷰 요청드립니다
kiworkshop/java-string-calculator pull request #12
Opened 2021-06-14 19:33 UTC by jiwoo-kimm

안녕하세요!

문자열 계산기 과제 제출합니다. 리뷰 부탁드립니다!

2021-06-16 11:37 UTC, me0768 requested changes
안녕하세요 지우선생님!
전반적으로 코드 매우 클린하고 구현도 잘 해주셨네요.
몇개 코멘트를 남겨보았습니다 ㅎㅎ 확인부탁드려요~

2021-06-16 11:37 UTC, me0768 commented on src/main/java/calculator/Splitter.java
> +    private static final int TRIMMED_TEXT = 2;
저 숫자 자체가 구분자, 텍스트는 아니어서 `CUSTOM_DELIMITER_INDEX`나 `CUSTOM_DELIMITER_GROUP_INDEX` 와 같이 용도를 구분할 수 있는 단어를 네이밍에 추가해주면 좋을 것 같습니다

2021-06-16 11:37 UTC, me0768 commented on src/main/java/calculator/Splitter.java
> +        updateIfCustomDelimiterExists();
생성자에서 필드에 할당을 한 다음에 다시 update를 하도록 구현하신 이유가 있을까요 ?

2021-06-16 11:37 UTC, me0768 commented on src/main/java/calculator/StringCalculator.java
> +        return text == null || text.isEmpty();
아실수도 있지만 참고로 알려드리면 
라이브러리 추가해서 쓸 수 있는 [StringUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html) 사용하면 간편하게 isEmpty나 isBlank로 처리 가능합니다.

`text == null` 이건 `Objects.isNull()`로도 쓸 수 있어요. 참고만 해주세요 :)

2021-06-16 11:37 UTC, me0768 commented on src/main/java/calculator/StringCalculator.java
> +            validatePositiveNumber(token);
추상화를 잘 해주셨네요. 코드가 깔끔하고 잘 읽혀요.

2021-06-16 11:37 UTC, me0768 commented on src/main/java/calculator/StringCalculator.java
> +        Splitter splitter = new Splitter(text);
split 메서드 안에서 새로운 객체를 생성하고 있네요. 위의 `splitAndSum()`을 빈값 없이 제대로 호출할때마다 Splitter 객체가 생성될텐데, 만약에  문자열 계산기 어플리케이션을 실제로 배포하고 이 메서드가 엄청 많이 호출되면 무슨 일이 생길까요?

2021-06-16 18:38 UTC, jiwoo-kimm commented on src/main/java/calculator/Splitter.java
> +    private static final int TRIMMED_TEXT = 2;
넵! 두 상수 모두 이름 변경했습니다

2021-06-16 18:52 UTC, jiwoo-kimm commented on src/main/java/calculator/Splitter.java
> +        updateIfCustomDelimiterExists();
기본값을 먼저 할당하고 변경해야 하는 경우에만 값을 변경하도록 하기 위해서 이렇게 했습니다! 새로운 text가 주어질 때마다 꼭 해야 하는 작업이니까 생성자에서 update 호출을 하도록 했어요..!

2021-06-16 18:54 UTC, jiwoo-kimm commented on src/main/java/calculator/StringCalculator.java
> +        return text == null || text.isEmpty();
둘 다 몰랐는데 이 기회에 알아놓겠습니다!

2021-06-16 18:54 UTC, jiwoo-kimm commented on src/main/java/calculator/StringCalculator.java
> +            validatePositiveNumber(token);
감사합니다 😄

2021-06-16 19:16 UTC, jiwoo-kimm commented on src/main/java/calculator/StringCalculator.java
> +        Splitter splitter = new Splitter(text);
별거 없는 일회용 객체인데도 엄청 많이 만들어서 메모리도 낭비되고 성능이 떨어질 것 같네요..!
사실 제가 각종 상수들이 Calculator 클래스에 죄다 모여 있는게 보기 싫어서 Splitter 클래스를 만들었던 거였거든요. 그래서 Splitter도 유지하면서 말씀하신 문제를 해결하기 위해서는, 그냥 split기능 수행하는 static 메서드 하나만 두면 될 것 같은데 어떨까요?

2021-06-17 15:05 UTC, me0768 commented on src/main/java/calculator/StringCalculator.java
> +        Splitter splitter = new Splitter(text);
네 좋습니다👏

2021-06-17 15:06 UTC, me0768 commented
고민 많이 하신 흔적이 보여요 :)  머지하겠습니다!

2021-06-17 15:06 UTC, merged