문자열 계산기
kiworkshop/java-string-calculator pull request #13
Opened 2021-06-15 13:44 UTC by Ariel429

문자열 계산기 리뷰 요청드립니다
감사합니다!

2021-06-16 08:02 UTC, KIMSIYOUNG requested changes
안녕하세요 정애선생님! 

요구사항에 맞게 잘 구현해주셨네요 👏 

고민해보면 좋을 것들이 몇 가지 있어서 코멘트 남겼습니다! 확인 부탁드릴게용

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    private static final String numbers = "^[0-9]*$";
[[오라클 코드 컨벤션]](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)에서 상수는 대문자로 정의하고 있네요🙂 

추가로, `numbers` 라는 네이밍은 숫자컬렉션을 의미할 것 같은데요! 조금 더 의미를 잘 드러낼 수 있는 네이밍을 고려해보면 좋을 것 같습니다.

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    public static int splitAndSum(String text){
[과제 요구사항 > 프로그래밍 요구사항](https://www.notion.so/kiworkshop/1-9eddec5a30244b31a486c72a570fa825)을 보면 메소드가 한 가지 일만 하도록 만들라는 요구사항이 있는데요!

해당 메소드는 분리/합계 두 가지 일을 하고 있어요! 조금 더 메소드를 작게 나눠보는건 어떨까요?

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    private static int validateAndSum(String[] tokens) {
`splitAndSum`과 `validateAndSum` 메소드를 모두 `static` 으로 선언하신 이유가 있으실까요?

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +            if (!Pattern.matches(numbers, token)) {
`프로그래밍 요구사항에 Depth를 2에서 1로 줄여라` 라는 부분이 있는데요! 

Depth를 줄이려면 어떤 방법들이 있을까요?

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/test/java/StringCalculatorTest.java
> +        result = StringCalculator.splitAndSum("");
아래와 같은 문자열이 들어오는 경우도 테스트에 추가하면 좋을 것 같아요! 
- 공백이 여러칸인 경우 "공백공백" (공백이 자동으로 줄어드네요....)
- 제대로 된 입력값이지만 사이사이에 공백이 있는 경우 "1,       공백        2"

테스트를 추가하셔도 되고, `Junit5 Parameterized Test`라는 키워드로 한 번 검색해보시면 좋은 예제들이 있을 것 같습니다🙂

2021-06-16 08:02 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +                throw new RuntimeException();
28번 라인과, 33번 라인 모두 `RuntimeException`을 던지고 있는데요! 

예외 로그에 라인수가 남지만, 로그만 봐서는(코드를 안 보고) 어떤 이유로 예외가 발생한지 알기 힘들 것 같아요!

예외를 통해 어떤 오류가 있는지 좀 더 명확하게 할 수 있는 방법은 어떤게 있을까요?

2021-06-24 13:14 UTC, Ariel429 commented on src/main/java/StringCalculator.java
> +    private static final String numbers = "^[0-9]*$";
넵 이름 규칙 읽어본 뒤에 수정했습니다

2021-06-24 13:15 UTC, Ariel429 commented on src/main/java/StringCalculator.java
> +    public static int splitAndSum(String text){
splitAndSum(String text)메서드는 저희 샘플로 테스트 코드가 주어졌는데, 거기서 가져와서 만들다보니 이름이 그렇게 지어진거 같습니다 ㅎㅎ

2021-06-24 13:16 UTC, Ariel429 commented on src/main/java/StringCalculator.java
> +    private static int validateAndSum(String[] tokens) {
위 코멘트와 비슷하게 sample코드에서 발전시키다 보니 그렇게 static으로 선언했고, 특별한 이유가 있지는 않은데 
시영 선생님께서 추천하시는 다른 방법이 있으실까요?

2021-06-24 13:17 UTC, Ariel429 commented on src/main/java/StringCalculator.java
> +            if (!Pattern.matches(numbers, token)) {
해당 과제에서는 stream()을 사용해서 Depth를 줄이는 방식으로 수정해봤습니다!

2021-06-24 13:18 UTC, Ariel429 commented on src/main/java/StringCalculator.java
> +                throw new RuntimeException();
예외발생의 이유를 프린트해주면 좋을것같네요 ㅎㅎ 피드백 감사합니다

2021-06-24 13:18 UTC, Ariel429 commented on src/test/java/StringCalculatorTest.java
> +        result = StringCalculator.splitAndSum("");
1주차 과제는 test를 직접 작성하지 않았지만 Parameterized Test를 살펴보도록 하겠습니다!

2021-06-24 14:13 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    private static final String numbers = "^[0-9]*$";
푸시해주시면 확인할게요🙂

2021-06-24 14:14 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    public static int splitAndSum(String text){
아하! 감사합니다ㅎㅎ

2021-06-24 14:24 UTC, KIMSIYOUNG commented on src/main/java/StringCalculator.java
> +    private static int validateAndSum(String[] tokens) {
네네! 스태틱 메소드와 인스턴스 메소드의 용도에 대해서 찾아보면 좋을 것 같아서 말씀드렸습니다🙂

1주차 요구사항은 아니지만, 해당 작업을 다른 클래스에게 위임하고 해당 클래스에 메시지를 보내는 방식으로 하면 좋을 것 같다고 생각했습니다! 아래와 같은 느낌으로 생각했습니다!

```java
Validator validator = new Validator();

validator.validate(tokens);

Results results = new Results(tokens);

return results.calculateSum();
```

2021-06-24 14:38 UTC, KIMSIYOUNG approved these changes
훨씬 코드가 깔끔해졌네요!

아래의 부분을 깜빡하고 놓치신거 같아서 요거만 개인적으로 반영해주세요🙏

고생하셨습니다! 다음 미션도 화이팅입니닷🙂

- `DEFAULT_NUMBERS` 요 부분이 사용되지 않고 있어요 확인해주세요🙂
- 예외에 메시지를 프린트하셨다고 하셨는데 아직 예외 메시지가 비어있어요!

2021-06-25 00:08 UTC, merged