Eoeh04
kiworkshop/java-string-calculator pull request #8
Opened 2021-06-13 03:30 UTC by eunii

[문자열 계산기] 제출합니다

2021-06-13 04:14 UTC, wbluke requested changes
빠르게 구현해 주셨네요 ㅎㅎ 👍 
소소한 코멘트 남겨보았는데요, 수정 후 재요청 부탁드려요 🙂

2021-06-13 04:14 UTC, wbluke commented on src/main/java/calculator/StringCalculator.java
> +    }
임시 테스트를 위해 만든 main 메서드로 보이는데요, 실제 프로덕션 코드에는 남기지 않는 것이 좋겠습니다 :)

2021-06-13 04:14 UTC, wbluke commented on src/main/java/calculator/StringCalculator.java
> +        if(stringNumber == null || stringNumber.isEmpty())  return 0;
(mac 기준) `Cmd + Option + L` 단축키로 코드 라인과 import를 자동 정리할 수 있습니다 ㅎㅎ
코드는 여러 사람이 함께 작업하는 문서의 역할도 하기 때문에 IDE에서 제공하는 자동정렬 기능을 습관화하면 좋을 것 같아요 :)

2021-06-13 04:14 UTC, wbluke commented on src/main/java/calculator/StringCalculator.java
> +        return numbers;
```suggestion
        return Stream.of(stringNumber.split(customDelimiter))
                .mapToInt(Integer::parseInt)
                .toArray();
```

- Stream은 가독성을 위해 한줄에 한 행위씩 선언하는 것이 좋습니다
- 바로 return 해도 되는 구조네요 :)

2021-06-13 23:16 UTC, eunii commented
1차 코멘트 반영

2021-06-15 12:25 UTC, wbluke approved these changes
수정해주신 부분 확인했습니다 ㅎㅎ
머지할게요~ 🙂 
(자동정렬 기능도 다음 미션 때 꼭 활용해 보세요 :) )

2021-06-15 12:26 UTC, merged